[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Bin Lookup Api Python"
authors = [{name = "Ajuly4003", email = "info@bxis.app"}]
dynamic = ["1.0.0", "Bin Lookup With Python"]
